import type { UiLanguage } from '@wrn/ui-language';
const en = {
  title: 'Content coverage',
  current: 'Current original-source links',
  snapshot: 'Feed published',
  newest: 'Newest included article',
  included: 'Included links',
  excluded: 'Excluded feed entries',
  pending: 'Source endpoints awaiting review',
  warning:
    'Links and recorded titles do not imply editorial verification or reuse rights. Full text, images, audio and logos require separate admission.',
  stale: 'This saved snapshot is more than 24 hours old. A live refresh has not been verified.',
  unknown: 'Coverage for this directory revision has not been verified.',
  unavailable: 'Coverage could not be checked.',
  pendingLabel: 'Unverified source · original link only',
  matchedLabel: 'Source profile available · item rights remain separate',
  reasons: 'Exclusion reasons',
  more: 'Browse all news links',
  original: 'Read the original publication',
};
type Copy = typeof en;
const catalogs: Record<UiLanguage, Copy> = {
  en,
  de: {
    title: 'Inhaltsabdeckung',
    current: 'Aktuelle Links zu Originalquellen',
    snapshot: 'Feed veröffentlicht',
    newest: 'Neuester aufgenommener Artikel',
    included: 'Aufgenommene Links',
    excluded: 'Ausgeschlossene Feedeinträge',
    pending: 'Quellenendpunkte mit ausstehender Prüfung',
    warning:
      'Links und erfasste Titel bedeuten keine redaktionelle Prüfung oder Wiederverwendungsrechte. Volltexte, Bilder, Audio und Logos benötigen eine gesonderte Aufnahme.',
    stale:
      'Dieser gespeicherte Stand ist älter als 24 Stunden. Eine aktuelle Live-Aktualisierung ist nicht bestätigt.',
    unknown: 'Die Abdeckung dieser Verzeichnisrevision ist nicht geprüft.',
    unavailable: 'Die Abdeckung konnte nicht geprüft werden.',
    pendingLabel: 'Ungeprüfte Quelle · nur Originallink',
    matchedLabel: 'Quellenprofil vorhanden · Einzelrechte bleiben getrennt',
    reasons: 'Ausschlussgründe',
    more: 'Alle Nachrichtenlinks öffnen',
    original: 'Originalveröffentlichung lesen',
  },
  es: {
    ...en,
    title: 'Cobertura de contenido',
    current: 'Enlaces actuales a fuentes originales',
    snapshot: 'Publicación del feed',
    newest: 'Artículo incluido más reciente',
    included: 'Enlaces incluidos',
    excluded: 'Entradas excluidas',
    pending: 'Fuentes pendientes de revisión',
    warning:
      'Los enlaces y títulos no implican verificación editorial ni derechos de reutilización. Textos, imágenes, audio y logos requieren admisión separada.',
    stale: 'Esta copia tiene más de 24 horas. No se ha verificado una actualización en vivo.',
    unknown: 'La cobertura de esta revisión no está verificada.',
    unavailable: 'No se pudo comprobar la cobertura.',
    pendingLabel: 'Fuente no verificada · solo enlace original',
    matchedLabel: 'Perfil disponible · derechos por artículo separados',
    reasons: 'Motivos de exclusión',
    more: 'Ver todos los enlaces',
    original: 'Leer la publicación original',
  },
  fr: {
    ...en,
    title: 'Couverture des contenus',
    current: 'Liens actuels vers les sources originales',
    snapshot: 'Publication du flux',
    newest: 'Article inclus le plus récent',
    included: 'Liens inclus',
    excluded: 'Entrées exclues',
    pending: 'Sources en attente de vérification',
    warning:
      'Les liens et titres ne garantissent ni vérification éditoriale ni droits de réutilisation. Textes, images, audio et logos exigent une admission distincte.',
    stale: 'Cette copie date de plus de 24 heures. Aucune actualisation en direct n’est vérifiée.',
    unknown: 'La couverture de cette révision n’est pas vérifiée.',
    unavailable: 'La couverture n’a pas pu être vérifiée.',
    pendingLabel: 'Source non vérifiée · lien original uniquement',
    matchedLabel: 'Profil disponible · droits individuels distincts',
    reasons: 'Motifs d’exclusion',
    more: 'Voir tous les liens',
    original: 'Lire la publication originale',
  },
  it: {
    ...en,
    title: 'Copertura dei contenuti',
    current: 'Link attuali alle fonti originali',
    snapshot: 'Pubblicazione del feed',
    newest: 'Articolo incluso più recente',
    included: 'Link inclusi',
    excluded: 'Voci escluse',
    pending: 'Fonti in attesa di verifica',
    warning:
      'Link e titoli non implicano verifica editoriale o diritti di riutilizzo. Testi, immagini, audio e loghi richiedono ammissione separata.',
    stale: 'Questa copia ha più di 24 ore. Nessun aggiornamento in tempo reale è verificato.',
    unknown: 'La copertura di questa revisione non è verificata.',
    unavailable: 'Impossibile verificare la copertura.',
    pendingLabel: 'Fonte non verificata · solo link originale',
    matchedLabel: 'Profilo disponibile · diritti individuali separati',
    reasons: 'Motivi di esclusione',
    more: 'Vedi tutti i link',
    original: 'Leggi la pubblicazione originale',
  },
  pt: {
    ...en,
    title: 'Cobertura do conteúdo',
    current: 'Links atuais para fontes originais',
    snapshot: 'Publicação do feed',
    newest: 'Artigo incluído mais recente',
    included: 'Links incluídos',
    excluded: 'Entradas excluídas',
    pending: 'Fontes aguardando revisão',
    warning:
      'Links e títulos não implicam verificação editorial ou direitos de reutilização. Textos, imagens, áudio e logotipos exigem admissão separada.',
    stale: 'Esta cópia tem mais de 24 horas. Nenhuma atualização ao vivo foi verificada.',
    unknown: 'A cobertura desta revisão não foi verificada.',
    unavailable: 'Não foi possível verificar a cobertura.',
    pendingLabel: 'Fonte não verificada · apenas link original',
    matchedLabel: 'Perfil disponível · direitos individuais separados',
    reasons: 'Motivos de exclusão',
    more: 'Ver todos os links',
    original: 'Ler a publicação original',
  },
  ru: {
    ...en,
    title: 'Охват материалов',
    current: 'Актуальные ссылки на первоисточники',
    snapshot: 'Лента опубликована',
    newest: 'Самая новая включённая статья',
    included: 'Включённые ссылки',
    excluded: 'Исключённые записи',
    pending: 'Источники, ожидающие проверки',
    warning:
      'Ссылки и заголовки не означают редакционной проверки или прав на использование. Тексты, изображения, аудио и логотипы требуют отдельного допуска.',
    stale: 'Эта копия старше 24 часов. Обновление в реальном времени не подтверждено.',
    unknown: 'Охват этой версии не проверен.',
    unavailable: 'Не удалось проверить охват.',
    pendingLabel: 'Непроверенный источник · только ссылка',
    matchedLabel: 'Профиль доступен · права на статью проверяются отдельно',
    reasons: 'Причины исключения',
    more: 'Все новостные ссылки',
    original: 'Читать оригинальную публикацию',
  },
  el: {
    ...en,
    title: 'Κάλυψη περιεχομένου',
    current: 'Τρέχοντες σύνδεσμοι στις αρχικές πηγές',
    snapshot: 'Δημοσίευση ροής',
    newest: 'Νεότερο άρθρο που περιλαμβάνεται',
    included: 'Σύνδεσμοι που περιλαμβάνονται',
    excluded: 'Εξαιρούμενες καταχωρίσεις',
    pending: 'Πηγές που αναμένουν έλεγχο',
    warning:
      'Οι σύνδεσμοι και οι τίτλοι δεν συνεπάγονται συντακτικό έλεγχο ή δικαιώματα επαναχρησιμοποίησης. Κείμενα, εικόνες, ήχος και λογότυπα απαιτούν ξεχωριστή έγκριση.',
    stale:
      'Αυτό το αντίγραφο είναι παλαιότερο από 24 ώρες. Δεν έχει επαληθευτεί ζωντανή ενημέρωση.',
    unknown: 'Η κάλυψη αυτής της έκδοσης δεν έχει ελεγχθεί.',
    unavailable: 'Δεν ήταν δυνατός ο έλεγχος κάλυψης.',
    pendingLabel: 'Μη ελεγμένη πηγή · μόνο αρχικός σύνδεσμος',
    matchedLabel: 'Διαθέσιμο προφίλ · ξεχωριστά δικαιώματα άρθρου',
    reasons: 'Λόγοι εξαίρεσης',
    more: 'Όλοι οι σύνδεσμοι ειδήσεων',
    original: 'Διαβάστε την αρχική δημοσίευση',
  },
  tr: {
    ...en,
    title: 'İçerik kapsamı',
    current: 'Özgün kaynaklara güncel bağlantılar',
    snapshot: 'Akış yayını',
    newest: 'Dahil edilen en yeni makale',
    included: 'Dahil edilen bağlantılar',
    excluded: 'Hariç tutulan kayıtlar',
    pending: 'İnceleme bekleyen kaynaklar',
    warning:
      'Bağlantılar ve başlıklar editoryal doğrulama veya yeniden kullanım hakkı anlamına gelmez. Metin, görsel, ses ve logolar ayrı kabul gerektirir.',
    stale: 'Bu kopya 24 saatten eski. Canlı güncelleme doğrulanmadı.',
    unknown: 'Bu sürümün kapsamı doğrulanmadı.',
    unavailable: 'Kapsam kontrol edilemedi.',
    pendingLabel: 'Doğrulanmamış kaynak · yalnızca özgün bağlantı',
    matchedLabel: 'Profil mevcut · makale hakları ayrı',
    reasons: 'Hariç tutma nedenleri',
    more: 'Tüm haber bağlantıları',
    original: 'Özgün yayını oku',
  },
};
export const getProjectionCopy = (language: string): Copy => catalogs[language as UiLanguage] ?? en;
