import type { UiLanguage } from '@wrn/ui-language';

const keys = [
  'editorialCredit',
  'today',
  'last24Hours',
  'reports',
  'languages',
  'regions',
  'sources',
  'coverage',
  'edition',
  'editionIntro',
  'openEdition',
  'close',
  'solidarityIntro',
  'notes',
  'illustrationCredit',
  'illustrationCaption',
  'noteTitle',
  'metadataNotice',
  'versions',
  'originalHeadline',
  'copyLink',
  'copied',
  'shareFailed',
  'textSize',
  'savedNews',
  'clearNews',
  'capacity',
] as const;
type Copy = Readonly<Record<(typeof keys)[number], string>>;
const values: Record<UiLanguage, readonly string[]> = {
  de: [
    'Die Startauswahl der App · Kurztexte und Schlagzeilen von WRN · Originalbeiträge verlinkt',
    'Heute bei WRN',
    'Letzte 24 Stunden',
    'Meldungen im geprüften Nachrichtenstand',
    'Sprachen',
    'Regionen',
    'Quellen',
    'Bis zu 160 Meldungen der letzten sieben Tage.',
    'Tagesausgabe',
    'Die Meldungen aus dem App-Briefing kompakt lesen.',
    'Ausgabe öffnen',
    'Schließen',
    'Geprüfte Anlaufstellen und die private Briefwerkstatt.',
    'WRN-Lesenotizen zu den Originalbeiträgen.',
    'WRN · KI-generierte Illustration',
    'Thematische WRN-Illustration. Kein Foto des berichteten Ereignisses.',
    'WRN-Lesenotiz',
    'Der vollständige Originaltext ist hier nicht freigegeben. Du kannst ihn bei der Quelle lesen.',
    'Übersetzen · WRN-Sprachversion',
    'Original-Schlagzeile',
    'Link kopieren',
    'Link kopiert.',
    'Teilen nicht möglich. Du kannst den Link unten kopieren.',
    'Textgröße',
    'Gespeicherte Nachrichten',
    'Nachrichten-Lesedaten löschen',
    'Der lokale Nachrichtenspeicher ist voll. Entferne zuerst einen Eintrag.',
  ],
  en: [
    'The App’s Home selection · Reading notes and headlines by WRN · Original articles linked',
    'Today at WRN',
    'Last 24 hours',
    'Reports in the reviewed news snapshot',
    'Languages',
    'Regions',
    'Sources',
    'Up to 160 reports from the last seven days.',
    'Daily edition',
    'Read the reports from the App briefing together.',
    'Open edition',
    'Close',
    'Reviewed support contacts and the private letter workshop.',
    'WRN reading notes about the original articles.',
    'WRN · AI-generated illustration',
    'Thematic WRN illustration. Not a photograph of the reported event.',
    'WRN reading note',
    'The complete original text is not cleared for display here. You can read it at the source.',
    'Translate · WRN language version',
    'Original headline',
    'Copy link',
    'Link copied.',
    'Sharing is unavailable. You can copy the link below.',
    'Text size',
    'Saved news',
    'Delete news reading data',
    'Local news storage is full. Remove an entry first.',
  ],
  es: [
    'La selección de inicio de la app · Notas y titulares de WRN · Artículos originales enlazados',
    'Hoy en WRN',
    'Últimas 24 horas',
    'Noticias del registro revisado',
    'Idiomas',
    'Regiones',
    'Fuentes',
    'Hasta 160 noticias de los últimos siete días.',
    'Edición diaria',
    'Lee juntas las noticias del resumen de la app.',
    'Abrir edición',
    'Cerrar',
    'Contactos de apoyo revisados y taller privado de cartas.',
    'Notas de lectura de WRN sobre los artículos originales.',
    'WRN · Ilustración generada por IA',
    'Ilustración temática de WRN. No es una fotografía del acontecimiento.',
    'Nota de lectura de WRN',
    'El texto original completo no está autorizado para mostrarse aquí. Puedes leerlo en la fuente.',
    'Traducir · Versión de WRN',
    'Titular original',
    'Copiar enlace',
    'Enlace copiado.',
    'No se puede compartir. Puedes copiar el enlace de abajo.',
    'Tamaño del texto',
    'Noticias guardadas',
    'Eliminar los datos de lectura de noticias',
    'El almacenamiento local está lleno. Elimina primero una entrada.',
  ],
  fr: [
    'La sélection d’accueil de l’app · Notes et titres de WRN · Articles originaux liés',
    'Aujourd’hui chez WRN',
    'Dernières 24 heures',
    'Actualités du relevé vérifié',
    'Langues',
    'Régions',
    'Sources',
    'Jusqu’à 160 actualités des sept derniers jours.',
    'Édition quotidienne',
    'Lisez ensemble les actualités du résumé de l’app.',
    'Ouvrir l’édition',
    'Fermer',
    'Contacts d’aide vérifiés et atelier de lettres privé.',
    'Notes de lecture de WRN sur les articles originaux.',
    'WRN · Illustration générée par IA',
    'Illustration thématique de WRN. Ce n’est pas une photo de l’événement.',
    'Note de lecture WRN',
    'Le texte original intégral n’est pas autorisé à être affiché ici. Vous pouvez le lire à la source.',
    'Traduire · Version WRN',
    'Titre original',
    'Copier le lien',
    'Lien copié.',
    'Le partage est indisponible. Vous pouvez copier le lien ci-dessous.',
    'Taille du texte',
    'Actualités enregistrées',
    'Effacer les données de lecture des actualités',
    'Le stockage local est plein. Supprimez d’abord une entrée.',
  ],
  it: [
    'La selezione iniziale dell’app · Note e titoli di WRN · Articoli originali collegati',
    'Oggi su WRN',
    'Ultime 24 ore',
    'Notizie nel registro verificato',
    'Lingue',
    'Regioni',
    'Fonti',
    'Fino a 160 notizie degli ultimi sette giorni.',
    'Edizione quotidiana',
    'Leggi insieme le notizie del riepilogo dell’app.',
    'Apri edizione',
    'Chiudi',
    'Contatti di supporto verificati e laboratorio privato di lettere.',
    'Note di lettura WRN sugli articoli originali.',
    'WRN · Illustrazione generata dall’IA',
    'Illustrazione tematica WRN. Non è una fotografia dell’evento.',
    'Nota di lettura WRN',
    'Il testo originale completo non è autorizzato per la visualizzazione qui. Puoi leggerlo alla fonte.',
    'Traduci · Versione WRN',
    'Titolo originale',
    'Copia link',
    'Link copiato.',
    'Condivisione non disponibile. Puoi copiare il link qui sotto.',
    'Dimensione del testo',
    'Notizie salvate',
    'Elimina i dati di lettura delle notizie',
    'La memoria locale è piena. Rimuovi prima una voce.',
  ],
  pt: [
    'A seleção inicial da app · Notas e títulos da WRN · Artigos originais ligados',
    'Hoje na WRN',
    'Últimas 24 horas',
    'Notícias no registo revisto',
    'Idiomas',
    'Regiões',
    'Fontes',
    'Até 160 notícias dos últimos sete dias.',
    'Edição diária',
    'Lê em conjunto as notícias do resumo da app.',
    'Abrir edição',
    'Fechar',
    'Contactos de apoio revistos e oficina privada de cartas.',
    'Notas de leitura da WRN sobre os artigos originais.',
    'WRN · Ilustração gerada por IA',
    'Ilustração temática da WRN. Não é uma fotografia do acontecimento.',
    'Nota de leitura WRN',
    'O texto original completo não está autorizado para apresentação aqui. Podes lê-lo na fonte.',
    'Traduzir · Versão WRN',
    'Título original',
    'Copiar ligação',
    'Ligação copiada.',
    'A partilha não está disponível. Podes copiar a ligação abaixo.',
    'Tamanho do texto',
    'Notícias guardadas',
    'Eliminar dados de leitura de notícias',
    'O armazenamento local está cheio. Remove primeiro uma entrada.',
  ],
  ru: [
    'Выбор главной страницы приложения · Заметки и заголовки WRN · Ссылки на оригиналы',
    'Сегодня в WRN',
    'Последние 24 часа',
    'Новости в проверенном снимке данных',
    'Языки',
    'Регионы',
    'Источники',
    'До 160 новостей за последние семь дней.',
    'Ежедневный выпуск',
    'Читайте вместе новости из обзора приложения.',
    'Открыть выпуск',
    'Закрыть',
    'Проверенные контакты поддержки и личная мастерская писем.',
    'Заметки WRN к оригинальным статьям.',
    'WRN · Иллюстрация, созданная ИИ',
    'Тематическая иллюстрация WRN. Это не фотография события.',
    'Заметка WRN',
    'Полный оригинальный текст не разрешён для публикации здесь. Его можно прочитать у источника.',
    'Перевести · Языковая версия WRN',
    'Оригинальный заголовок',
    'Копировать ссылку',
    'Ссылка скопирована.',
    'Поделиться не удалось. Можно скопировать ссылку ниже.',
    'Размер текста',
    'Сохранённые новости',
    'Удалить данные чтения новостей',
    'Локальное хранилище заполнено. Сначала удалите запись.',
  ],
  el: [
    'Η επιλογή αρχικής σελίδας της εφαρμογής · Σημειώσεις και τίτλοι WRN · Σύνδεσμοι πρωτοτύπων',
    'Σήμερα στο WRN',
    'Τελευταίες 24 ώρες',
    'Ειδήσεις στο ελεγμένο στιγμιότυπο',
    'Γλώσσες',
    'Περιοχές',
    'Πηγές',
    'Έως 160 ειδήσεις των τελευταίων επτά ημερών.',
    'Ημερήσια έκδοση',
    'Διαβάστε μαζί τις ειδήσεις της σύνοψης της εφαρμογής.',
    'Άνοιγμα έκδοσης',
    'Κλείσιμο',
    'Ελεγμένες επαφές υποστήριξης και ιδιωτικό εργαστήριο επιστολών.',
    'Σημειώσεις ανάγνωσης WRN για τα πρωτότυπα άρθρα.',
    'WRN · Εικονογράφηση με τεχνητή νοημοσύνη',
    'Θεματική εικονογράφηση WRN. Δεν είναι φωτογραφία του γεγονότος.',
    'Σημείωση ανάγνωσης WRN',
    'Το πλήρες πρωτότυπο κείμενο δεν έχει άδεια προβολής εδώ. Μπορείτε να το διαβάσετε στην πηγή.',
    'Μετάφραση · Γλωσσική έκδοση WRN',
    'Πρωτότυπος τίτλος',
    'Αντιγραφή συνδέσμου',
    'Ο σύνδεσμος αντιγράφηκε.',
    'Η κοινοποίηση δεν είναι διαθέσιμη. Αντιγράψτε τον σύνδεσμο παρακάτω.',
    'Μέγεθος κειμένου',
    'Αποθηκευμένες ειδήσεις',
    'Διαγραφή δεδομένων ανάγνωσης ειδήσεων',
    'Ο τοπικός χώρος είναι πλήρης. Αφαιρέστε πρώτα μια εγγραφή.',
  ],
  tr: [
    'Uygulamanın başlangıç seçkisi · WRN notları ve başlıkları · Özgün yazı bağlantıları',
    'Bugün WRN’de',
    'Son 24 saat',
    'İncelenen haber kaydındaki haberler',
    'Diller',
    'Bölgeler',
    'Kaynaklar',
    'Son yedi günden en fazla 160 haber.',
    'Günlük sayı',
    'Uygulama özetindeki haberleri birlikte oku.',
    'Sayıyı aç',
    'Kapat',
    'İncelenen destek iletişimleri ve özel mektup atölyesi.',
    'Özgün yazılar hakkında WRN okuma notları.',
    'WRN · Yapay zekâ ile oluşturulan illüstrasyon',
    'WRN tematik illüstrasyonu. Bildirilen olayın fotoğrafı değildir.',
    'WRN okuma notu',
    'Özgün yazının tamamının burada gösterim izni yok. Kaynağında okuyabilirsin.',
    'Çevir · WRN dil sürümü',
    'Özgün başlık',
    'Bağlantıyı kopyala',
    'Bağlantı kopyalandı.',
    'Paylaşım kullanılamıyor. Aşağıdaki bağlantıyı kopyalayabilirsin.',
    'Metin boyutu',
    'Kaydedilen haberler',
    'Haber okuma verilerini sil',
    'Yerel depolama dolu. Önce bir kaydı kaldır.',
  ],
};
export function getWebsiteHomeCopy(language: UiLanguage): Copy {
  return Object.fromEntries(keys.map((key, i) => [key, values[language][i]])) as Copy;
}
