/** Fixed public V1 facade. Capacity policy internals stay in the internal module. */
export {
  productionContentReleaseSchemaV1,
  productionContentDescriptorSchemaV1,
  productionArticleAdmissionSchemaV1,
  productionReadingDetailsSchemaV1,
  productionDiscoverIndexSchemaV1,
  productionArchiveLifecycleSchemaV1,
  productionWebsitePublicationSchemaV1,
  productionContractVersionV1,
  isProductionContentDescriptorV1,
  isProductionContentManifestV1,
  isProductionArchiveLifecycleV1,
  isConsistentProductionArchiveLifecycleV1,
  isProductionContentRevisionV1,
  resolveProductionContentLifecycleV1,
  createProductionContentSafetyLedger,
  isProductionContentSafetyLedgerV1,
  validateProductionContentReleaseV1,
  createValidatedProductionContentReleaseV1,
  resolveProductionContentArticleV1,
  createProductionArticleShareUrlV1,
  isProductionWebsitePublicationV1,
  validateProductionWebsitePublicationV1,
  // @ts-expect-error Node 24 executes this facade directly from TypeScript source.
} from './production-content-validation-internal.ts';
export type {
  ProductionArticleIdV1,
  ProductionReaderBlockV1,
  ProductionArticleV1,
  ProductionArticleAdmissionV1,
  ProductionReaderDetailsV1,
  ProductionDiscoverIndexV1,
  ProductionArchiveLifecycleV1,
  ProductionContentReleaseDocumentsV1,
  ProductionContentReleaseDescriptorV1,
  ProductionContentManifestV1,
  ProductionWebsitePublicationV1,
  ProductionContentReleaseInputV1,
  ProductionContentValidationResultV1,
  ProductionContentReadyV1,
  ProductionContentSafetyLedgerV1,
  ProductionContentResolutionV1,
  ProductionContentLifecycleResolutionInputV1,
} from './production-content-validation-internal.ts';
